import Head from "next/head";
import Navbar from "../components/Navbar";

export default function About() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>About</h3>
    </div>
  );
}
