import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import { useSession } from "next-auth/client";
import MaterialTable from "material-table";
import { useTheme } from "styled-components";
import { Grid_2 } from "./../components/Basic/Grid/basic_grid.js";

export default function Home() {
  const theme = useTheme();
  const [session, loading] = useSession();
  const [projects, setProjects] = useState([]);
  const getProjects = async () => {
    try {
      const res = await axios.get("api/getProjects");
      setProjects(
        res.data.map((item) => ({ ...item, counts: item.analyzer.length }))
      );
      console.log(res.data);
    } catch (err) {
      console.log(err.message);
    }
  };

  useEffect(() => {
    getProjects();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid_2>
        <div>asdqwe</div>
        <MaterialTable
          style={{
            marginTop: "3rem",
            background: theme.colors.light,
            borderRadius: "0",
            boxShadow: "none",
          }}
          columns={[
            { title: "Projekt", field: "name" },
            { title: "Erstellt", field: "createdAt", type: "datetime" },
            { title: "# Geräte", field: "counts", type: "numeric" },
          ]}
          data={projects}
          options={{
            rowStyle: {
              borderBottom: "2px solid white",
            },
            headerStyle: {
              background: theme.colors.dark + 80,
              color: "white",
            },
          }}
          title="Projekte"
        />
      </Grid_2>
    </>
  );
}
